### ISSUE TITLE
mkv support

### ISSUE THREAD

**Issue by rom1504** [feross/render-media#13]
Chrome seems to support mkv files. They can be read by webtorrent-app (https://github.com/feross/webtorrent-app/blob/fc425e422154f3f79876e44f6c128b8a086d3c0f/renderer/lib/torrent-player.js#L18)

Doesn't that mean mkv could be added there https://github.com/feross/render-media/blob/master/index.js#L14 so instant.io would support mkv videos ? (at least in chrome)

**Comment by feross** [comment]
Yes, let's give this a try.

**Comment by feross** [comment]
This will never be perfect, since we're just guessing the codec, but it might play some .mkv videos. The real solution is for someone to add support for .mkv to @jhiesey's `videostream`.

**Comment by feross** [comment]
https://github.com/feross/render-media/commit/94e0d3e215156d9dd2623aaa7dd68f254000230b

2.5.0
