### ISSUE TITLE
Feature for audio-video

### ISSUE THREAD

**Issue by isaactzab** [feross/render-media#20]
I don't know if this is the right place to talk about it or is scope of this project, but I think that there are a lot of features for video/audio that could be implemented in browser side like video preview, video convert, crop, cut or whatever...
I found this : https://bgrins.github.io/videoconverter.js/demo/ and maybe could help to develop it.

**Comment by feross** [comment]
This library is very focused: It just renders a stream of data into a dom element. That other library is cool, but this isn't the place for those features.

**Comment by guanzo** [comment]
Is it possible to extract the first frame of the video and set it as the `<video>` poster? With autoplay disabled, the video has a white background and it looks broken. Could anyone point me to a library or have any idea how to do it myself?

**Comment by feross** [comment]
You might be able to make something work with https://github.com/feross/capture-frame
