### ISSUE TITLE
how to specify render strategy?

### ISSUE THREAD

**Issue by ralyodio** [feross/render-media#24]
This module is used by webtorrent -- I'm trying to figure out how to specify the render strategy.

      const file = torrent.files[0]
      file.appendTo('#player')

...this is pretty much all I have to go off. 

How do I tell it to use `videostream` strategy or one of the others. It seems to always use `blob:`?

**Comment by fiatjaf** [comment]
That's not possible. Everything is decided based on the file extension. See https://github.com/feross/render-media/blob/8153697cbc4309bfec3d3f6a475f889da834a58f/index.js#L144-L154.

What is the extension of the file you're dealing with?

**Comment by feross** [comment]
We first try to use `videostream`, but if that fails, or isn't possible due to the file extension, then we try a naive mediasource implementation. Finally, if that fails, blob is used.

**Comment by ralyodio** [comment]
I'm trying to load a .mkv video file. As soon as it gets added to dom it crashes the page. and I see a blob url which I thought was ignored for large files (this a 1GB+ video file).

I see its not configurable I misread the doc -- but still can't play this .mkv file.

**Comment by feross** [comment]
Blob URLs are also used by the MediaSource API. Sorry that this is not working for your MKV file. Video stuff is really tricky to get perfectly right, and that's when you completely control the videos you're playing back, like YouTube and Vimeo does. If this library isn't working for you, you're on your own to figure out the problem. Send a PR if you find what is causing the issue.

**Comment by ralyodio** [comment]
probably not encoded properly.
