### ISSUE TITLE
Render a list of files (ex: mp4 + jpg + srt)

### ISSUE THREAD

**Issue by yciabaud** [feross/render-media#26]
I believe it would be useful to implement the rendering of a list of files together in an element. My use case is a torrent containing a mp4 video along with a poster and some srt files. We could render a nice video elem with sources, tracks...

I dont see another use case for now, do you think it would fit in this module?

**Comment by feross** [comment]
Given how complicated this module already is, I'd rather see this implemented as another package that depends on `render-media`.
