### ISSUE TITLE
ReadableStream weird behavior when starting to play a video

### ISSUE THREAD

**Issue by rllola** [feross/render-media#29]
I am using `render-media` to stream video that are downloading from libtorrent. I have noticed, when I start to play a mp4 video, a behavior that I can't understand and is producing some delay when starting to play the media.

Basically it is calling `createReadStream` 4 times at start with different offset value : 0, 32, 40 and one that correspond to the end of the file and when it is getting the value it is destroying the `readableStream`. I suppose it is the way the video player is getting the metadata but everytime it is adding me a delay of 400ms (time to get a chunk of data). Is it a normal behavior ? How could I avoid this ?

**Comment by feross** [comment]
You can't really control what parts of the video are needed. That is determined by where the metadata is located in the particular file that you're downloading.

Ideally, the torrent contains properly produced video files optimized for streaming so that all the metadata is available upfront.
