### ISSUE TITLE
Rotation metadata is ignored

### ISSUE THREAD

**Issue by kauffj** [feross/render-media#30]
[This file](https://spee.ch/5/cauliflower.mp4), which contains metadata indicating it is a vertical video, plays horizontally in `render-media`.

More details are available in [this issue](https://github.com/lbryio/lbry-app/issues/539#issuecomment-329376764).

**Comment by feross** [comment]
👋 Thanks for opening an issue. This project is a volunteer-run effort. I don't have any immediate plans to work on this issue, so I'm going to close it.

However, I noticed you appear to work for a for-profit company. Please consider asking your company to allocate resources toward fixing this issue and submitting a PR. I'll be happy to review any PR you contribute here. 😄 

Finally, if you lack the time or skills to fix this issue, you can hire me at my standard hourly rate. Contact me at [[my first name]@feross.org](mailto:) to discuss further.
