### ISSUE TITLE
Custom iframe src

### ISSUE THREAD

**Issue by btzr-io** [feross/render-media#39]
Allow to pass  a custom `iframe` src base path, 
this is helpful when rendering documents and other non-streamable file types 
using and external viewer: Like [viewer.js](http://viewerjs.org/) or mozzilla [pdf.js](https://github.com/mozilla/pdf.js/wiki/Setup-pdf.js-in-a-website#from-examples)

```JS
const source = `${customSource}?file=blob:src...`
<iframe src={source} />
```

**Comment by btzr-io** [comment]
@feross  Let me know if this feature should be added so I can work on a PR, 
otherwise I'll close this issue :v:

**Comment by feross** [comment]
Hey @btzr-io, can you explain what the use case is that you're trying to solve in more detail? I'm afraid I don't understand what problem this solves. Thanks!

**Comment by btzr-io** [comment]
Hi, I'm trying to display `non-streamable` files using a custom viewer because the browser can display it properly or in most cases it will prompt and ask to download the file, 
for example if I try to render a file like `data.csv` it would  be displayed inside an iframe as a plain text:
```
Year,Make,Model,Length
1997,Ford,E350,2.34
2000,Mercury,Cougar,2.38
```
But I need to use a custom viewer to be displayed as a table:

| Year | Make | Model | Length
| --- | --- | --- | --- |
| 1997 | Ford | E350 | 2.38  |
| 2000 | Mercury | Cougar | 2.34 |


``` HTML
<iframe src='/custom-viewer?file=blob:url' />
```
Is there a better way to handle this?

**Comment by btzr-io** [comment]
What I'm trying to say it's that I don't need the iframe
but just the `blob-url` so I can handle the rendering part.
```JS
render.blob(file, (blob) => { 
   // Callback to do something with the blob
   renderCustomViewer(blob)
})
```
@feross  Maybe this use case isn't  appropiate for `render-media`, Should I make my own module / fork ?

**Comment by btzr-io** [comment]
I'll use this: https://github.com/feross/stream-to-blob-url
