### ISSUE TITLE
Readme and autoplay issue with .render

### ISSUE THREAD

**Issue by mitra42** [feross/render-media#47]
Is there an issue with the Readme. 

It suggests
```
render.render(file, elem, [function callback (err, elem) {}])
Like render.append but renders directly into given element (or CSS selector).
```
And I was wondering why it didn't take the `opts` parameter (as part of figuring out why autoplay isn't happening) but I see in the code that it takes an optional `opts` parameter.

Is the code, the Readme, or my understand wrong ?

**Comment by mitra42** [comment]
Related, it seems that 
a) autoplay default (set in parseOpts) appears to be false while docs say its true

And autoplay doesn't seem to work even when set :-( but that probably should be a different isue.

**Comment by mitra42** [comment]
Doing some research ... 
That `render()` doesn't save the options like append does - I added them within the callback passed to `renderMedia`. 
Then ... `onLoadStart` is called and trys to do `elem.play()`
But that doesn't play - probably because 0% is downloaded at this point.
The obvious place would be in `onCanPlay` but despite that handler being added inside useVideoStream it doesnt appear to ever get triggered , i.e. `onCanPlay()` doesn't get called.

@jhiesey is this a videostream issue ?

**Comment by jhiesey** [comment]
The readme is wrong. `.render()` can also take four arguments. i.e. `render.render(file, elem, opts, callback)`

**Comment by jhiesey** [comment]
I'll investigate the `onCanPlay` issue too.

**Comment by jhiesey** [comment]
I see `onCanPlay` getting called. Do you have an example where it's not?

But I do see `Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first.` which relates to the recent browser policy change I mentioned.

**Comment by feross** [comment]
@mitra42 I just fixed the documentation issues you raised in your first two comments. As for your third comment, I think John pointed out the correct reason. Autoplay won't work due to a new browser restriction. It might be best to let the user click-to-play.

Alternatively you can autoplay if the video is muted and unmute on the first click. This is what the WebTorrent homepage does. https://webtorrent.io

**Comment by mitra42** [comment]
Thanks -looks like its working now, though I can't see where its turning it on, or what changed to fix it  (in my code or yours) :-(

**Comment by feross** [comment]
It's possible that your browser learned you like to listen to audio on the dweb site and is allowing it by default.

If you use Chrome, you can check to see if this is the case by visiting `chrome://media-engagement/`. If "Is High" shows "Yes" then the site is now whitelisted by default. The indeterminism of these new browser restrictions makes it tough to test, unfortunately. :(
