### ISSUE TITLE
Raspberry Pi performance

### ISSUE THREAD

**Issue by kodxana** [feross/render-media#49]
It is possible to increase performance for raspberry pi?
Raspberry Pi is powerful to watch 1080p 60 fps video but in app with this plugin videos lag so much.

**Comment by iohzrd** [comment]
Have you tried testing videos on the pi in chrome/chromium? In my experience, the performance is pretty bad(IE definitely not 60fps at 1080p). I suspect this is because chromium doesn't properly utilize hardware acceleration on the pi...

**Comment by feross** [comment]
cc @jhiesey who maintains `videostream`. Is there any reason that performance would be especially bad on a Pi that you can think of?
