### ISSUE TITLE
Usage with React

### ISSUE THREAD

**Issue by mitra42** [feross/render-media#55]
I've been using render-media to render streams (both webtorrent, and images) into our code and it works great. I now have to embed something into a React application. 

Unfortunately react frowns on pretty much anything else touching the HTML tree, so i'm trying to figure out how to use Render-Media with a react component - note that I don't need to actually build a react-component for render-media, its more of a question of whether anyone has figured out how to use render-media within a react-component.

**Comment by mitra42** [comment]
OK - complicated ... but got it to work: Sanitized code is below.  Note the use of the "ref" callback from React to get the DOM Element to render into 
```
import React from 'react'
import PropTypes from 'prop-types'
export default class extends React.Component { 
    static propTypes = { ...};
    constructor(props)
    {
        super(props);
        this.state = {  ... }
        this.loadImg = (enclosingspan) => // Defined as a closure so that can access identifier
            const file = {
                name: name,
                // Here goes your custom code that returns a function: f(opts) 
                createReadStream: f_createReadStream(this.identifier)  
        };
     // Render into supplied element 
    // - note have to use append, as RenderMedia.render doesnt work on firefox for images
    // the cb can be used to set attributes and/or add children.
        RenderMedia.append(file, enclosingspan, cb);  
    }
    
    render() {
            return <span ref={this.loadImg}></span>
    }
}
```

**Comment by feross** [comment]
Just saw this issue. Glad you got it figured out @mitra42!
