### ISSUE TITLE
Resizing of images on Firefox

### ISSUE THREAD

**Issue by mitra42** [feross/render-media#56]
There is a significant difference in render-media.render between Firefox and Chrome

I've got some code that builds a page with a number of JPG images and then fetches the images (peer to peer)  and renders them using render-media. 

If I use a `<img>` and .render to render into them, then on Chrome as the images are added the layout is recalculated as each image comes in, and the final page looks "correct".  

But on Firefox it doesn't trigger the re-layout., resizing the window triggers that re-layout and it only then looks correct. 

Up until now, I've been using a `<span>` and using .append to render an image inside the span, but that's triggering some CSS compatability issues so I'd love to go back to .render for both browsers. 

Any ideas ... 

Note - I seem to remember that changing the "src" of an `<img>` tag in Firefox also works differently than Chrome so it might be related.

**Comment by feross** [comment]
Hi @mitra42, this definitely seems like a bug in Firefox. I was able to find these questions:

- https://stackoverflow.com/questions/2826799/firefox-wont-change-image-source
- https://stackoverflow.com/questions/11809985/force-firefox-to-reload-image-after-img-src-change

But it's not clear how we should fix it in `render-media` since we use `blob:` urls. I don't believe we can add a query parameter to these urls.

I wasn't able to find an open issue on BugZilla about this. Perhaps filing a Firefox issue would yield more info from the Firefox team?

**Comment by mitra42** [comment]
Yes - this was a bug from almost a year ago, and I notice it crept back into my code - for example https://dweb.me/arc/archive.org/details/mbid-c0c1245c-f8b3-3dba-9310-82052adfa73a doesnt use rendermedia, but uses the same functionality that rendermedia does for images i.e. 
```
streamToBlobURL(res.createReadStream(),  mimetype, cb) 
```
That url works on Chrome, but not on Firefox and the Inspector shows the <img tag loaded and even shows the image it should be showing. 

The computed styles are width=0 height=0 but none of the edits I've tried in inspector fix it (I'm not an expert at debugging in Firefox, use Chrome for my debugging which is why I didn't notice that my code stopped working in Firefox again.

**Comment by mitra42** [comment]
I've filed a bugzilla issue https://bugzilla.mozilla.org/show_bug.cgi?id=1576523 .
Its intermitent - depending a lot on styles, and I tracked down at least one case to whether maxHeight and maxWidth are set, if they are - then the image doesnt resize, if omitted then it resizes. There might be other triggers, this was just one bizarre difference I was able to narrow it down to.

**Comment by mitra42** [comment]
OK - I killed that as it turned out not to be quite true, the problem was in the behavior of img.complete which is different in Firefox and Chrome, that was interacting with resizing code that resized the container based on the size of the image ONCE ITS COMPLETE. On Firefox it was complete and 0x0 prior to render-media (or React) loading it. On Chrome its not complete till after the successful load.

**Comment by feross** [comment]
Since it seems like this is a Firefox bug, I'm going to close this issue. But I'll follow along with the browser bug reports in case there's something we can do. Please leave a comment or open a new issue if anything changes or if there's something we can do to fix this in `render-media`.

**Comment by mitra42** [comment]
To be clear the Firefox team have it and think its a Chrome issue : 
For reference: Firefox issue https://bugzilla.mozilla.org/show_bug.cgi?id=1577991 and Chrome issue (filed by the firefox team) https://bugs.chromium.org/p/chromium/issues/detail?id=1000273

**Comment by feross** [comment]
I see. In any case, I don't think we're using the `.complete` property in `render-media` so it's still not an issue that we can fix here. But thanks for clarifying!

**Comment by mitra42** [comment]
i think there may have been two issues - when the post was made in December I think Firefox was not re-rendering. At some point I disabled my workaround and it was fixed but ... when you posted this 13 days ago I went and checked again, and surprisingly some things were rendering and some not - it turned out that at least in that case, it appears now that this is the .complete difference between FF and Chrome, rather than an issue with RenderMedia's interaction with FF, so I agree this issue is closed, but worth watching.
