### ISSUE TITLE
eventlistener cleanup

### ISSUE THREAD

**Issue by ddumont** [feross/render-media#69]
rendering multiple video streams to the same element causes errors to be generated from the old stream as the new one is added.  The number of errors thrown rises each time you change the stream, as each time it adds new listeners.

```js
    function useVideostream () {
      debug('Use `videostream` package for ' + file.name)
      prepareElem()
      elem.addEventListener('error', fallbackToMediaSource)
      elem.addEventListener('loadstart', onLoadStart)
      elem.addEventListener('canplay', onCanPlay)
      videostream(file, elem)
    }
```

I'm using webtorrent and calling `file.renderTo`
Is there a way that it could remove this fallback listener?   is there a way to destroy the render and have it clean up?

**Comment by feross** [comment]
Thanks for the issue. There's currently no way to destroy a render, other than removing the DOM element from the page and using a new one. There's an issue to track adding this, but unfortunately I do not have time to fix this myself at the moment.

See: https://github.com/feross/render-media/issues/32
